ALTER TABLE album DROP CONSTRAINT FK_album_artistId
ALTER TABLE album DROP CONSTRAINT FK_album_genreId
DROP TABLE artist
DROP TABLE album
DROP TABLE genre
DROP TABLE song
DROP TABLE playlist
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
